// Code generated by protoc-gen-grpc-gateway-client. DO NOT EDIT.
// source: service.proto

package pb

import (
	context "context"
	fmt "fmt"
	gateway "github.com/akuity/grpc-gateway-client/pkg/grpc/gateway"
	url "net/url"
)

// MyServiceGatewayClient is the interface for MyService service client.
type MyServiceGatewayClient interface {
	GetMessage(context.Context, *RequestStruct) (*ResponseStruct, error)
}

func NewMyServiceGatewayClient(c gateway.Client) MyServiceGatewayClient {
	return &myServiceGatewayClient{
		gwc: c,
	}
}

type myServiceGatewayClient struct {
	gwc gateway.Client
}

func (c *myServiceGatewayClient) GetMessage(ctx context.Context, req *RequestStruct) (*ResponseStruct, error) {
	gwReq := c.gwc.NewRequest("GET", "/v1/getmessage")
	q := url.Values{}
	q.Add("clientType", fmt.Sprintf("%v", req.ClientType))
	gwReq.SetQueryParamsFromValues(q)
	return gateway.DoRequest[ResponseStruct](ctx, gwReq)
}
